-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TYPE "public"."word_status" AS ENUM('NONE', 'TO_LEARN', 'LEARNED', 'HIDDEN');--> statement-breakpoint
CREATE TABLE "word" (
	"word" text PRIMARY KEY NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"raw" jsonb NOT NULL,
	"status" "word_status" DEFAULT 'NONE' NOT NULL,
	"user" text NOT NULL,
	"ai_definition" jsonb,
	"ai_definition_request_start_date" date
);
--> statement-breakpoint
CREATE TABLE "training_spelling" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "training_spelling_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"word" text NOT NULL,
	"answer" text NOT NULL,
	"errors_count" smallint NOT NULL,
	"user" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pronunciation" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pronunciation_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"word" text NOT NULL,
	"recognised_text" text NOT NULL,
	"success" boolean NOT NULL,
	"user" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "training" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "training_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"word" text NOT NULL,
	"is_success" boolean NOT NULL,
	"definition" text NOT NULL,
	"user" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "user" (
	"login" text PRIMARY KEY NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"passphrase" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "word" ADD CONSTRAINT "word_user_fkey" FOREIGN KEY ("user") REFERENCES "public"."user"("login") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "training_spelling" ADD CONSTRAINT "training_spelling_user_fkey" FOREIGN KEY ("user") REFERENCES "public"."user"("login") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "training_spelling" ADD CONSTRAINT "training_spelling_word_fkey" FOREIGN KEY ("word") REFERENCES "public"."word"("word") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pronunciation" ADD CONSTRAINT "pronunciation_user_fkey" FOREIGN KEY ("user") REFERENCES "public"."user"("login") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pronunciation" ADD CONSTRAINT "pronunciation_word_fkey" FOREIGN KEY ("word") REFERENCES "public"."word"("word") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "training" ADD CONSTRAINT "training_user_fkey" FOREIGN KEY ("user") REFERENCES "public"."user"("login") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "training" ADD CONSTRAINT "training_word_fkey" FOREIGN KEY ("word") REFERENCES "public"."word"("word") ON DELETE no action ON UPDATE no action;
*/